databases:
  - name: micronaut
    databaseName: budget_app_ww09
    user: posgres

services:
  - type: web
    name: rails-budget-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app_ww09
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false