databases:
  - name: ezra
    databaseName: ezra
    user: ezra

services:
  - type: web
    name: rails-budget-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ezra
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false