databases:
  - name: micronaut
    databaseName: micronaut_83ti
    user: micronaut_83ti_user

services:
  - type: web
    name: rails-budget-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micronaut_83ti
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false